### ISSUE TITLE
Email sended or send fail - how to know about?

### ISSUE THREAD

**Issue by jrborbars** [marlin-dev/fastapi-mail#2]
Since the docs is the README itself, I don't see ANY example regarding the email send fail. How can treat this case with this library?

**Comment by marlin-dev** [comment]
I will be updating everything soon, I will add docs separately.  Regarding your case, if you connect to your mail server successfully and the library does not throw an error this means you can send an email. But if the recipient or given domain is wrong library cannot detect this case. I have tried some different mail servers, an example if the recipient did not found, Gmail backs you with a specific message.  This specific to mail server not to the library.

GMAIL:
```
address not found
--
Your message wasn't delivered to "mail_address" because the address couldn't be found, or is unable to receive mail.

**Comment by jrborbars** [comment]
Thank you for your reply. Is there a specific error or exception in case of fail to connect? Or a verbose debug to logging? Thanks in advance.

**Comment by marlin-dev** [comment]
Yes definitely, the library uses smtplib, on initializing it checks connections parameters, if there is an error on the connection it will raise an error for connection regarding the following errors it can happen either port, password, domain, used service, tls, or ssl is wrongly set.
